In [1]:
import pandas as pd
import numpy as np

# Outdoor Games

# Cricket Data Cleaning

In [2]:
cric_df1 = pd.read_csv("Outdoor/Cricket/asiacup.csv")
cric_df1.head()

,Team,Opponent,Format,Ground,Year,Toss,Selection,Runs,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Player Of The Match,Result
0,Pakistan,Sri Lanka,ODI,Sharjah,1984,Lose,Batting,187.0,9.0,9.0,3.0,21.0,4.06,52.04,47.0,5.0,26.0,2.0,Roy Dias,Lose
1,Sri Lanka,Pakistan,ODI,Sharjah,1984,Win,Bowling,190.0,5.0,11.0,1.0,26.0,4.36,68.51,57.0,9.0,21.0,3.0,Roy Dias,Win
2,India,Sri Lanka,ODI,Sharjah,1984,Win,Bowling,97.0,0.0,9.0,0.0,14.0,4.47,60.48,51.0,10.0,8.0,3.0,Surinder Khanna,Win
3,Sri Lanka,India,ODI,Sharjah,1984,Lose,Batting,96.0,10.0,7.0,0.0,8.0,2.34,25.74,38.0,0.0,14.0,0.0,Surinder Khanna,Lose
4,India,Pakistan,ODI,Sharjah,1984,Win,Batting,188.0,4.0,13.0,3.0,17.0,4.08,60.21,56.0,10.0,5.0,3.0,Surinder Khanna,Win

In [3]:
cric_df1.isnull().sum()

Team                         0
Opponent                     0
Format                       0
Ground                       0
Year                         0
Toss                         0
Selection                    0
Runs                         2
Wicket Lost                  2
Fours                        2
Sixes                        2
Extras                       2
Run Rate                     2
Avg Bat Strike Rate          2
Highest Score                2
Wicket Taken                 2
Given Extras                 2
Highest Individual wicket    2
Player Of The Match          2
Result                       0
dtype: int64

In [4]:
columns_to_fill = [
    "Team",
    "Opponent",
    "Format",
    "Ground",
    "Year",
    "Toss",
    "Selection",
    "Runs",
    "Wicket Lost",
    "Fours",
    "Sixes",
    "Extras",
    "Run Rate",
    "Avg Bat Strike Rate",
    "Highest Score",
    "Wicket Taken",
    "Given Extras",
    "Highest Individual wicket",
    "Player Of The Match",
    "Result"
]

for col in columns_to_fill:
    if col in cric_df1.columns:
        cric_df1[col] = cric_df1[col].fillna(0)

In [5]:
cric_df1[columns_to_fill].isnull().sum()

Team                         0
Opponent                     0
Format                       0
Ground                       0
Year                         0
Toss                         0
Selection                    0
Runs                         0
Wicket Lost                  0
Fours                        0
Sixes                        0
Extras                       0
Run Rate                     0
Avg Bat Strike Rate          0
Highest Score                0
Wicket Taken                 0
Given Extras                 0
Highest Individual wicket    0
Player Of The Match          0
Result                       0
dtype: int64

In [6]:
cric_df1.head()

,Team,Opponent,Format,Ground,Year,Toss,Selection,Runs,Wicket Lost,Fours,Sixes,Extras,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Given Extras,Highest Individual wicket,Player Of The Match,Result
0,Pakistan,Sri Lanka,ODI,Sharjah,1984,Lose,Batting,187.0,9.0,9.0,3.0,21.0,4.06,52.04,47.0,5.0,26.0,2.0,Roy Dias,Lose
1,Sri Lanka,Pakistan,ODI,Sharjah,1984,Win,Bowling,190.0,5.0,11.0,1.0,26.0,4.36,68.51,57.0,9.0,21.0,3.0,Roy Dias,Win
2,India,Sri Lanka,ODI,Sharjah,1984,Win,Bowling,97.0,0.0,9.0,0.0,14.0,4.47,60.48,51.0,10.0,8.0,3.0,Surinder Khanna,Win
3,Sri Lanka,India,ODI,Sharjah,1984,Lose,Batting,96.0,10.0,7.0,0.0,8.0,2.34,25.74,38.0,0.0,14.0,0.0,Surinder Khanna,Lose
4,India,Pakistan,ODI,Sharjah,1984,Win,Batting,188.0,4.0,13.0,3.0,17.0,4.08,60.21,56.0,10.0,5.0,3.0,Surinder Khanna,Win

In [7]:
columns_to_drop = ["Team", "Opponent", "Format", "Ground", "Year", "Toss", "Selection", "Extras", "Given Extras", "Player Of The Match", "Result"]
 
cric_df1.drop(columns=columns_to_drop, inplace=True)

In [8]:
cric_df1.head()

,Runs,Wicket Lost,Fours,Sixes,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Highest Individual wicket
0,187.0,9.0,9.0,3.0,4.06,52.04,47.0,5.0,2.0
1,190.0,5.0,11.0,1.0,4.36,68.51,57.0,9.0,3.0
2,97.0,0.0,9.0,0.0,4.47,60.48,51.0,10.0,3.0
3,96.0,10.0,7.0,0.0,2.34,25.74,38.0,0.0,0.0
4,188.0,4.0,13.0,3.0,4.08,60.21,56.0,10.0,3.0

In [9]:
cric_df2 = pd.read_csv("Outdoor/Cricket/ICC Mens T20 Worldcup.csv")
cric_df2.head()

,Match No.,Date,Venue,1st Team,2nd Team,Stage,Toss Winning,Toss Decision,First Innings Score,Fall of wickets First Innings,...,Winners,Method,Won by,Winning Margin,Top Scorer,Highest Score,Best Bowler,Best Bowler Figure(Wickets Taken),Best Bowler Figure(Runs Recieved),Player Of The Match
0,1st,"Saturday,June 1,2024","Grand Prairie Stadium, Dallas",Canada,United State Of America,Group A,United State Of America,Fielding,194,5,...,United State Of America,Normal Match,Wickets,7,Aaron Jones,94,Dilon Heyliger,1,19,Aaron Jones
1,2nd,"Sunday,June 2,2024","Providence Stadium, Guyana",Papua New Guinea,Afghanistan,Group C,Afghanistan,Fielding,95,10,...,Afghanistan,Normal Match,Wickets,7,Gulbadin Naib,49,Fazalhaq Farooqi,3,16,Fazalhaq Farooqi
2,3rd,"Sunday,June 2,2024","Kensington Oval, Bridgetown, Barbados",Oman,Namibia,Group B,Namibia,Fielding,109,10,...,Namibia,Normal Match,Wickets,4,Jan Frylinck,45,Mehran Khan,3,7,David Wiese
3,4th,"Monday,June 3,2024","Nassau County International Cricket Stadium, N...",Sri Lanka,South Africa,Group D,Sri Lanka,Batting,77,10,...,South Africa,Normal Match,Wickets,6,Quinton de Kock,20,Anrich Nortje,4,7,Anrich Nortje
4,5th,"Monday,June 3,2024","Providence Stadium, Guyana",Afghanistan,Uganda,Group C,Uganda,Fielding,183,5,...,Afghanistan,Normal Match,Runs,125,Rahmanullah Gurbaz,76,Fazalhaq Farooqi,5,9,Fazalhaq Farooqi

In [10]:
cric_df2.isnull().sum()

Match No.                            0
Date                                 0
Venue                                0
1st Team                             0
2nd Team                             0
Stage                                0
Toss Winning                         0
Toss Decision                        0
First Innings Score                  0
Fall of wickets First Innings        0
Second Innings Score                 0
Fall of wickets Second Innings       0
Winners                              0
Method                               0
Won by                               0
Winning Margin                       0
Top Scorer                           0
Highest Score                        0
Best Bowler                          0
Best Bowler Figure(Wickets Taken)    0
Best Bowler Figure(Runs Recieved)    0
Player Of The Match                  0
dtype: int64

In [11]:
columns_to_fill = [
    'Match No.',
    'Date',
    'Venue',
    '1st Team',
    '2nd Team',
    'Stage',
    'Toss Winning',
    'Toss Decision',
    'First Innings Score',
    'Fall of wickets First Innings',
    'Second Innings Score',
    'Fall of wickets Second Innings',
    'Winners',
    'Method',
    'Won by',
    'Winning Margin',
    'Top Scorer',
    'Highest Score',
    'Best Bowler',
    'Best Bowler Figure(Wickets Taken)',
    'Best Bowler Figure(Runs Recieved)',
    'Player Of The Match'
]

for col in columns_to_fill:
    if col in cric_df2.columns:
        cric_df2[col] = cric_df2[col].fillna(0)

In [12]:
cric_df2[columns_to_fill].isnull().sum()

Match No.                            0
Date                                 0
Venue                                0
1st Team                             0
2nd Team                             0
Stage                                0
Toss Winning                         0
Toss Decision                        0
First Innings Score                  0
Fall of wickets First Innings        0
Second Innings Score                 0
Fall of wickets Second Innings       0
Winners                              0
Method                               0
Won by                               0
Winning Margin                       0
Top Scorer                           0
Highest Score                        0
Best Bowler                          0
Best Bowler Figure(Wickets Taken)    0
Best Bowler Figure(Runs Recieved)    0
Player Of The Match                  0
dtype: int64

In [13]:
columns_to_drop = ['Match No.', 'Date', 'Venue', '1st Team', '2nd Team', 'Stage', 'Toss Winning', 'Toss Decision', 'First Innings Score', 
                   'Fall of wickets First Innings', 'Second Innings Score', 'Fall of wickets Second Innings', 'Winners', 'Method', 'Won by', 'Winning Margin', 
                   'Top Scorer', 'Best Bowler Figure(Wickets Taken)', 'Best Bowler Figure(Runs Recieved)', 'Player Of The Match'
]

cric_df2.drop(columns=columns_to_drop, inplace=True)

In [14]:
cric_df2.head()

  Highest Score       Best Bowler
0            94    Dilon Heyliger
1            49  Fazalhaq Farooqi
2            45       Mehran Khan
3            20     Anrich Nortje
4            76  Fazalhaq Farooqi

In [15]:
cric_df3 = pd.read_csv("Outdoor/Cricket/batsman data odi.csv")
cric_df3.head()

,Player Name,Country,Time Period,Matches,Played,Not Outs,Runs,Highest Score,Batting Average,Balls Faced,Strike Rate,Centuries,Fifties,Ducks,Fours,Sixes
0,ST Jayasuriya,Sri Lanka,1990-2008,25,24,1,1220,130,53.04,1190,102.52,6,3,1,139,23
1,KC Sangakkara,Sri Lanka,2004-2014,24,23,1,1075,121,48.86,1272,84.51,4,8,2,107,7
2,SR Tendulkar,India,1990-2012,23,21,2,971,114,51.10,1136,85.47,2,7,0,108,8
3,Shoaib Malik,Pakistan,2000-2018,17,15,3,786,143,65.50,867,90.65,3,3,0,76,8
4,RG Sharma,India,2008-2018,22,21,5,745,111,46.56,877,84.94,1,6,1,60,17

In [16]:
cric_df3.isnull().sum()

Player Name        0
Country            0
Time Period        0
Matches            0
Played             0
Not Outs           0
Runs               0
Highest Score      0
Batting Average    0
Balls Faced        0
Strike Rate        0
Centuries          0
Fifties            0
Ducks              0
Fours              0
Sixes              0
dtype: int64

In [17]:
columns_to_fill = [
    'Country',
    'Time Period',
    'Matches',
    'Played',
    'Not Outs',
    'Runs',
    'Highest Score',
    'Batting Average',
    'Balls Faced',
    'Strike Rate',
    'Centuries',
    'Fifties',
    'Ducks',
    'Fours',
    'Sixes'
]

for col in columns_to_fill:
    if col in cric_df3.columns:
        cric_df3[col] = cric_df3[col].fillna(0)

In [18]:
columns_to_drop = ['Country', 'Time Period', 'Matches', 'Ducks',
]
cric_df3.drop(columns=columns_to_drop, inplace=True)

In [19]:
cric_df3.head()

,Player Name,Played,Not Outs,Runs,Highest Score,Batting Average,Balls Faced,Strike Rate,Centuries,Fifties,Fours,Sixes
0,ST Jayasuriya,24,1,1220,130,53.04,1190,102.52,6,3,139,23
1,KC Sangakkara,23,1,1075,121,48.86,1272,84.51,4,8,107,7
2,SR Tendulkar,21,2,971,114,51.10,1136,85.47,2,7,108,8
3,Shoaib Malik,15,3,786,143,65.50,867,90.65,3,3,76,8
4,RG Sharma,21,5,745,111,46.56,877,84.94,1,6,60,17

In [20]:
cric_df1["format"] = "AsiaCup"
cric_df2["format"] = "T20WC"

In [21]:
match_df = pd.concat([cric_df1, cric_df2], ignore_index=True)

In [22]:
match_df.isna().sum()

Runs                          55
Wicket Lost                   55
Fours                         55
Sixes                         55
Run Rate                      55
Avg Bat Strike Rate           55
Highest Score                  0
Wicket Taken                  55
Highest Individual wicket     55
format                         0
Best Bowler                  254
dtype: int64

In [23]:
batsman_agg = cric_df3.groupby("Played").agg({
    "Runs": "mean",
    "Strike Rate": "mean",
    "Fours": "mean",
    "Sixes": "mean"
}).reset_index()

In [24]:
final_cric = match_df.merge(
    batsman_agg,
    on="Runs",
    how="left"
)

In [25]:
# Target Variable is Runs or Wicket Taken

In [26]:
final_cric.head()

,Runs,Wicket Lost,Fours_x,Sixes_x,Run Rate,Avg Bat Strike Rate,Highest Score,Wicket Taken,Highest Individual wicket,format,Best Bowler,Played,Strike Rate,Fours_y,Sixes_y
0,187.0,9.0,9.0,3.0,4.06,52.04,47.0,5.0,2.0,AsiaCup,NaN,NaN,NaN,NaN,NaN
1,190.0,5.0,11.0,1.0,4.36,68.51,57.0,9.0,3.0,AsiaCup,NaN,NaN,NaN,NaN,NaN
2,97.0,0.0,9.0,0.0,4.47,60.48,51.0,10.0,3.0,AsiaCup,NaN,NaN,NaN,NaN,NaN
3,96.0,10.0,7.0,0.0,2.34,25.74,38.0,0.0,0.0,AsiaCup,NaN,NaN,NaN,NaN,NaN
4,188.0,4.0,13.0,3.0,4.08,60.21,56.0,10.0,3.0,AsiaCup,NaN,NaN,NaN,NaN,NaN

In [31]:
final_cric = final_cric.ffill()
final_cric.isna().sum()

Runs                           0
Wicket Lost                    0
Fours_x                        0
Sixes_x                        0
Run Rate                       0
Avg Bat Strike Rate            0
Highest Score                  0
Wicket Taken                   0
Highest Individual wicket      0
format                         0
Best Bowler                  254
Played                        72
Strike Rate                   72
Fours_y                       72
Sixes_y                       72
dtype: int64

In [33]:
# final_cric.to_csv('cleaned_cricket.csv', index=False)

# Football Data Cleaning

In [34]:
foot_df1 = pd.read_csv("Outdoor/Football/players_22.csv", low_memory=False)
foot_df1.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value,wage,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [35]:
foot_df1.isnull().sum()

sofifa_id               0
player_url              0
short_name              0
long_name               0
player_positions        0
                    ...
player_face_url         0
club_logo_url          61
club_flag_url          61
nation_logo_url     18480
nation_flag_url         0
Length: 110, dtype: int64

In [36]:
columns_to_drop = ['sofifa_id', 'player_url', 'short_name', 'long_name', 'dob', 'club_team_id', 'club_name', 'league_name', 'league_level', 
                   'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 
                   'nationality_name', 'nation_team_id', 'nation_position','nation_jersey_number', 'preferred_foot', 'skill_moves',	
                   'international_reputation',	'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 
                   'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys',
                   'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 
                   'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping',
                   'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning',
                   'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 
                   'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
                   'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls',	'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam',
                   'cam', 'ram', 'lm',	'lcm', 'cm', 'rcm',	'rm', 'lwb', 'ldm',	'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 
                   'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']    

foot_df1.drop(columns=columns_to_drop, inplace=True)

In [37]:
foot_df1.isnull().sum()

player_positions       0
overall                0
potential              0
value                 74
wage                  61
age                    0
height_cm              0
weight_kg              0
weak_foot              0
pace                2132
shooting            2132
passing             2132
dribbling           2132
defending           2132
physic              2132
dtype: int64

In [38]:
columns_to_fill = [
   'player_positions',
    'overall',
    'potential',
    'value',
    'wage',
    'age',
    'height_cm',
    'weight_kg',
    'weak_foot',
    'pace',
    'shooting',
    'passing',
    'dribbling',
    'defending',
    'physic'
]

for col in columns_to_fill:
    if col in foot_df1.columns:
        foot_df1[col] = foot_df1[col].fillna(0)

In [39]:
foot_df1.isnull().sum()

player_positions    0
overall             0
potential           0
value               0
wage                0
age                 0
height_cm           0
weight_kg           0
weak_foot           0
pace                0
shooting            0
passing             0
dribbling           0
defending           0
physic              0
dtype: int64

In [40]:
foot_df1.head()

,player_positions,overall,potential,value,wage,age,height_cm,weight_kg,weak_foot,pace,shooting,passing,dribbling,defending,physic
0,"RW, ST, CF",93,93,78000000.0,320000.0,34,170,72,4,85.0,92.0,91.0,95.0,34.0,65.0
1,ST,92,92,119500000.0,270000.0,32,185,81,4,78.0,92.0,79.0,86.0,44.0,82.0
2,"ST, LW",91,91,45000000.0,270000.0,36,187,83,4,87.0,94.0,80.0,88.0,34.0,75.0
3,"LW, CAM",91,91,129000000.0,270000.0,29,175,68,5,91.0,83.0,86.0,94.0,37.0,63.0
4,"CM, CAM",91,91,125500000.0,350000.0,30,181,70,5,76.0,86.0,93.0,88.0,64.0,78.0

In [41]:
foot_df2 = pd.read_csv("Outdoor/Football/FIFA23_official_data.csv")
foot_df2.head()

,Age,overall,potential,value,wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
0,27,87,88,€91M,115,Right,4,4,3,High/ Medium,...,Yes,"<span class=""pos pos28"">SUB","Jul 1, 2018",NaN,2026,189cm,82kg,€157M,8.0,NaN
1,27,86,87,€78.5M,€190K,Right,3,3,4,High/ High,...,Yes,"<span class=""pos pos15"">LCM","Jan 30, 2020",NaN,2026,179cm,69kg,€155M,8.0,NaN
2,30,85,85,€46.5M,€46K,Left,2,3,3,High/ High,...,No,"<span class=""pos pos7"">LB","Sep 14, 2020",NaN,2024,172cm,69kg,€97.7M,19.0,NaN
3,31,91,91,€91M,116,Right,4,5,4,High/ High,...,Yes,"<span class=""pos pos13"">RCM","Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17.0,NaN
4,25,86,89,€78.5M,€190K,Right,3,3,3,High/ High,...,Yes,"<span class=""pos pos13"">RCM","Sep 1, 2020",NaN,2026,172cm,68kg,€154.4M,23.0,NaN

In [42]:
foot_df2.columns

Index(['Age', 'overall', 'potential', 'value', 'wage', 'Preferred Foot',
       'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate',
       'Body Type', 'Real Face', 'Position', 'Joined', 'Loaned From',
       'Contract Valid Until', 'Height', 'Weight', 'Release Clause',
       'Kit Number', 'Best Overall Rating'],
      dtype='object')

In [43]:
columns_to_drop = [
    'Age',
    'Weak Foot',
    'Preferred Foot',
    'International Reputation', 
    'Skill Moves', 
    'Work Rate',
    'Body Type', 
    'Real Face', 
    'Position', 
    'Joined', 
    'Loaned From',
    'Contract Valid Until', 
    'Height', 
    'Weight', 
    'Release Clause',
    'Kit Number', 
    'Best Overall Rating'
]    

foot_df2.drop(columns=columns_to_drop, inplace=True)

In [44]:
foot_df2.isnull().sum()

overall      0
potential    0
value        0
wage         0
dtype: int64

In [45]:
foot_df2.head()

   overall  potential   value   wage
0       87         88    €91M    115
1       86         87  €78.5M  €190K
2       85         85  €46.5M   €46K
3       91         91    €91M    116
4       86         89  €78.5M  €190K

In [46]:
final_foot = pd.concat([foot_df1, foot_df2], axis=0)

In [47]:
# Overall is target variable

In [48]:
final_foot.isna().sum()

player_positions    17660
overall                 0
potential               0
value                   0
wage                    0
age                 17660
height_cm           17660
weight_kg           17660
weak_foot           17660
pace                17660
shooting            17660
passing             17660
dribbling           17660
defending           17660
physic              17660
dtype: int64

In [49]:
final_foot = final_foot.ffill()
final_foot.isna().sum()

player_positions    0
overall             0
potential           0
value               0
wage                0
age                 0
height_cm           0
weight_kg           0
weak_foot           0
pace                0
shooting            0
passing             0
dribbling           0
defending           0
physic              0
dtype: int64

In [50]:
# final_foot.to_csv('cleaned_foot.csv', index=False)

# Golf Data Cleaning

In [1708]:
golf_df1 = pd.read_csv("Outdoor/Golf/golf1.csv")
golf_df1.head()

,POS,PLAYER,SCORE,R1,R2,R3,R4,TOT,EARNINGS,FEDEX PTS,tournamentID
0,1,Geoff Ogilvy,-24,67,68,65,68,268,"$1,120,000.00",500.0,12009
1,T2,Davis Love III,-18,69,70,68,67,274,"$523,500.00",245.0,12009
2,T2,Anthony Kim,-18,71,68,68,67,274,"$523,500.00",245.0,12009
3,4,Sean O'Hair,-17,69,70,71,65,275,"$312,000.00",135.0,12009
4,5,Justin Leonard,-16,74,67,65,70,276,"$261,000.00",110.0,12009

In [1709]:
golf_df1.isnull().sum()

POS                0
PLAYER             0
SCORE              0
R1                 0
R2                 0
R3                 0
R4               366
TOT              288
EARNINGS         170
FEDEX PTS       2030
tournamentID       0
dtype: int64

In [1710]:
columns_to_fill = [
    'POS',
    'PLAYER',
    'SCORE',
    'R1',
    'R2',
    'R3',
    'R4',
    'TOT',
    'EARNINGS',
    'FEDEX PTS',
    'tournamentID'   
]

for col in columns_to_fill:
    if col in golf_df1.columns:
        golf_df1[col] = golf_df1[col].fillna(2)

In [1711]:
columns_to_drop = ['tournamentID', 'POS']    

golf_df1.drop(columns=columns_to_drop, inplace=True)

In [1712]:
golf_df1.head()

           PLAYER SCORE  R1  R2  R3  R4  TOT       EARNINGS  FEDEX PTS
0    Geoff Ogilvy   -24  67  68  65  68  268  $1,120,000.00      500.0
1  Davis Love III   -18  69  70  68  67  274    $523,500.00      245.0
2     Anthony Kim   -18  71  68  68  67  274    $523,500.00      245.0
3     Sean O'Hair   -17  69  70  71  65  275    $312,000.00      135.0
4  Justin Leonard   -16  74  67  65  70  276    $261,000.00      110.0

In [1713]:
golf_df3 = pd.read_csv("Outdoor/Golf/golf3.csv")
golf_df3.head()

,Id,year,date,name,course,City,State,Lat,Long,Course Par,...,day1high,day1avg,day1precip,day1wind,day2,day2low,day2high,day2avg,day2precip,day2wind
0,12014,2014,Oct 10 - 13,Frys.com Open,"CordeValle Golf Club - San Martin, CA.",San Martin,CA,37.09,-121.59,71,...,78.80,64.40,0.000000,12.5459,10/11/2014,53.60,84.20,65.84,0.0,6.2154
1,12015,2015,Oct 9 - 12,Frys.com Open,Silverado Resort and Spa (North Course) - Napa...,Napa,CA,38.30,-122.29,72,...,84.92,65.12,0.000000,9.2080,10/10/2015,57.20,77.00,64.04,0.0,11.0496
2,12016,2016,Oct 15 - 18,Frys.com Open,Silverado Resort and Spa (North Course) - Napa...,Napa,CA,38.30,-122.29,72,...,69.08,61.52,0.311024,15.5385,10/16/2016,53.06,64.94,60.08,0.0,11.5100
3,12017,2017,Oct 13 - 16,Safeway Open,Silverado Resort and Spa (North Course) - Napa...,Napa,CA,38.30,-122.29,72,...,73.94,53.78,0.000000,5.2946,10/14/2017,42.08,80.96,62.42,0.0,9.0929
4,12019,2019,Oct 4 - 7,Safeway Open,Silverado Resort and Spa (North Course) - Napa...,Napa,CA,38.30,-122.29,72,...,73.94,57.56,0.000000,11.5100,10/5/2019,41.00,80.06,58.64,0.0,5.4097

In [1714]:
golf_df3.isnull().sum()

Id               0
year             0
date             0
name             0
course           0
City             0
State            0
Lat              0
Long             0
Course Par       0
Winning Score    0
CutLine          0
day0             0
day0low          0
day0high         0
day0avg          0
day0precip       0
day0wind         0
day1             0
day1low          0
day1high         0
day1avg          0
day1precip       0
day1wind         0
day2             0
day2low          0
day2high         0
day2avg          0
day2precip       0
day2wind         0
dtype: int64

In [1715]:
columns_to_drop = ['Id', 'year', 'date', 'name', 'course', 'State', 'Lat', 'Long', 'Winning Score', 'CutLine', 'day0', 'day0low',
                   'day0high', 'day0avg', 'day0precip', 'day0wind', 'day1', 'day1low', 'day2', 
                   'day2low', 'day2high', 'day2avg', 'day2precip', 'day2wind']

golf_df3.drop(columns=columns_to_drop, inplace=True)

In [1716]:
golf_df3

                 City  Course Par  day1high  day1avg  day1precip  day1wind
0          San Martin          71     78.80    64.40    0.000000   12.5459
1                Napa          72     84.92    65.12    0.000000    9.2080
2                Napa          72     69.08    61.52    0.311024   15.5385
3                Napa          72     73.94    53.78    0.000000    5.2946
4                Napa          72     73.94    57.56    0.000000   11.5100
..                ...         ...       ...      ...         ...       ...
286            Blaine          71     84.02    78.08    0.015748   18.0707
287           Memphis          70     91.04    80.06    0.610236   12.4308
288  Lake Buena Vista          72     80.06    68.36    0.000000   13.3516
289        Greensboro          70     91.94    78.44    0.669291    9.0929
290       Jersey City          71     87.08    80.60    0.181102   19.5670

[291 rows x 6 columns]

In [1717]:
final_golf = pd.concat([golf_df1], axis=0)
final_golf

                PLAYER SCORE  R1  R2  R3  R4  TOT       EARNINGS  FEDEX PTS
0         Geoff Ogilvy   -24  67  68  65  68  268  $1,120,000.00      500.0
1       Davis Love III   -18  69  70  68  67  274    $523,500.00      245.0
2          Anthony Kim   -18  71  68  68  67  274    $523,500.00      245.0
3          Sean O'Hair   -17  69  70  71  65  275    $312,000.00      135.0
4       Justin Leonard   -16  74  67  65  70  276    $261,000.00      110.0
...                ...   ...  ..  ..  ..  ..  ...            ...        ...
61278       Adam Scott    -4  68  70  68  70  276    $550,000.00        2.0
61279    Corey Conners    -3  74  66  71  67  278    $540,000.00        2.0
61280         K.H. Lee    -1  68  72  69  70  279    $530,000.00        2.0
61281  Sahith Theegala     1  71  72  67  71  281    $520,000.00        2.0
61282  Scott Stallings     3  70  74  69  73  286    $510,000.00        2.0

[61283 rows x 9 columns]

In [1718]:
final_golf.isna().sum()

PLAYER       0
SCORE        0
R1           0
R2           0
R3           0
R4           0
TOT          0
EARNINGS     0
FEDEX PTS    0
dtype: int64

In [1719]:
 # final_golf.to_csv('cleaned_golf_data.csv', index=False)

# Rugby Data Cleaning

In [1599]:
rugby_df1 = pd.read_csv("Outdoor/rugby/rugby1.csv", encoding="latin1")
rugby_df1.head()

,racking,First-name,Name,Nationality,Position,age,tall(m),weight,start_career,club,...,National_match,National_W,National_D,National_L,National_starter,National_try,National_Points,National_min,yellow,red
0,1,Antoine,Dupont,France,Scrumhalf,27,1.74,86,2000.0,Toulouse,...,2,2,0,0,2,0,0,127,0,0
1,2,Ardie,Savea,New Zealand,Backrow,30,1.90,103,2013.0,Wellington Hurricanes,...,13,9,0,4,13,6,30,918,1,0
2,3,Pieter-Steph,Du Toit,South Africa,Backrow,32,2.00,116,2013.0,Toyota Verblitz,...,12,10,0,2,12,3,15,856,1,0
3,4,Caelen,Doris,Ireland,Backrow,26,193.00,106,2017.0,Leinster,...,15,12,0,2,12,3,15,1069,1,0
4,5,Eben,Etzebeth,South Africa,Secondrow,32,2.03,126,2013.0,sharks,...,12,10,0,2,11,1,5,603,2,0

In [1600]:
rugby_df1.isnull().sum()

racking                   0
First-name                0
Name                      0
Nationality               0
Position                  0
age                       0
tall(m)                   0
weight                    0
start_career              1
club                      0
Tournament                4
club-match                1
club_W                    1
club_D                    1
club_L                    1
club_starter              2
club_try                  1
club_points               1
club_Min                  2
other club tournament    18
other-match               2
other_W                   2
other_D                   2
other_L                   2
other_starter             2
other_try                 2
other_points              2
other_Min                 2
National_match            0
National_W                0
National_D                0
National_L                0
National_starter          0
National_try              0
National_Points           0
National_min              0
yellow                    0
red                       0
dtype: int64

In [1601]:
columns_to_fill = [
    'racking'
    'First-name',
    'Name',
    'Nationality',
    'Position',
    'age',
    'tall(m)',
    'weight',
    'start_career',
    'club',
    'Tournament',
    'club-match',
    'club_W',
    'club_D',
    'club_L',
    'club_starter',
    'club_try',
    'club_points',
    'club_Min',
    'other club tournament',
    'other-match',
    'other_W',
    'other_D',
    'other_L',
    'other_starter',
    'other_try',
    'other_points',
    'other_Min',
    'National_match',
    'National_W',
    'National_D',
    'National_L',
    'National_starter',
    'National_try',
    'National_Points',
    'National_min',
    'yellow card',
    'red card'
]

for col in columns_to_fill:
    if col in rugby_df1.columns:
        rugby_df1[col] = rugby_df1[col].fillna(0)

In [1602]:
rugby_df1.isnull().sum()

racking                  0
First-name               0
Name                     0
Nationality              0
Position                 0
age                      0
tall(m)                  0
weight                   0
start_career             0
club                     0
Tournament               0
club-match               0
club_W                   0
club_D                   0
club_L                   0
club_starter             0
club_try                 0
club_points              0
club_Min                 0
other club tournament    0
other-match              0
other_W                  0
other_D                  0
other_L                  0
other_starter            0
other_try                0
other_points             0
other_Min                0
National_match           0
National_W               0
National_D               0
National_L               0
National_starter         0
National_try             0
National_Points          0
National_min             0
yellow                   0
red                      0
dtype: int64

In [1603]:
columns_to_drop = ['racking', 'First-name', 'Name', 'Nationality', 'club', 'Tournament', 'club-match',
                   'club_W', 'club_D', 'club_L',
                   'club_starter',
                   'club_try', 'club_points', 'club_Min', 'other-match', 'other_W', 'other_D', 
                   'other_L', 'other_starter', 
                   'other_try', 'other_points', 'other_Min', 'National_match', 'National_D', 'National_starter',
                   'National_Points', 'National_min'
]

rugby_df1.drop(columns=columns_to_drop, inplace=True)

In [1604]:
rugby_df1.head()

,Position,age,tall(m),weight,start_career,other club tournament,National_W,National_L,National_try,yellow,red
0,Scrumhalf,27,1.74,86,2000.0,champions cup,2,0,0,0,0
1,Backrow,30,1.90,103,2013.0,0,9,4,6,1,0
2,Backrow,32,2.00,116,2013.0,0,10,2,3,1,0
3,Backrow,26,193.00,106,2017.0,champions cup,12,2,3,1,0
4,Secondrow,32,2.03,126,2013.0,Challenge Cup,10,2,1,2,0

In [1605]:
rugby_df3 = pd.read_csv("Outdoor/rugby/rugby3.csv")
rugby_df3.head()

,player_id,birthdate,pos,year,team,competition,pts,played,start,try,pen,dp,tr,yellow,red,min
0,esteban-abadie-4289,01/12/1997,Third Row,2022,Brive,Top 14,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0
1,esteban-abadie-4289,01/12/1997,Third Row,2021,Brive,European Rugby Challenge Cup,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0
2,esteban-abadie-4289,01/12/1997,Third Row,2021,Brive,Top 14,10.0,20.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,1185.0
3,esteban-abadie-4289,01/12/1997,Third Row,2020,Brive,European Rugby Challenge Cup,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,136.0
4,esteban-abadie-4289,01/12/1997,Third Row,2020,Brive,Top 14,0.0,8.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,315.0

In [1606]:
rugby_df3.isnull().sum()

player_id         0
birthdate      2494
pos              27
year              0
team              0
competition       0
pts             561
played          561
start           561
try             561
pen             561
dp              561
tr              561
yellow          561
red             561
min             561
dtype: int64

In [1607]:
columns_to_drop = ['player_id', 'birthdate', 'pos', 'dp', 'tr']

rugby_df3.drop(columns=columns_to_drop, inplace=True)

In [1608]:
rugby_df3.isnull().sum()

year             0
team             0
competition      0
pts            561
played         561
start          561
try            561
pen            561
yellow         561
red            561
min            561
dtype: int64

In [1609]:
columns_to_fill = [
    "year",
    "team",
    "competition",
    "pts",
    "played",
    "start"
    "try"
    "pen"
    "yellow",
    "red",
    "min"
]

for col in columns_to_fill:
    if col in rugby_df3.columns:
        rugby_df3[col] = rugby_df3[col].fillna(3)

In [1610]:
rugby_df3.head()

,year,team,competition,pts,played,start,try,pen,yellow,red,min
0,2022,Brive,Top 14,0.0,2.0,2.0,0.0,0.0,0.0,0.0,160.0
1,2021,Brive,European Rugby Challenge Cup,0.0,1.0,0.0,0.0,0.0,0.0,0.0,29.0
2,2021,Brive,Top 14,10.0,20.0,14.0,2.0,0.0,0.0,0.0,1185.0
3,2020,Brive,European Rugby Challenge Cup,0.0,2.0,2.0,0.0,0.0,0.0,0.0,136.0
4,2020,Brive,Top 14,0.0,8.0,3.0,0.0,0.0,1.0,0.0,315.0

In [1611]:
final_rugby = pd.concat([rugby_df1, rugby_df3], axis=0)
final_rugby.head()

,Position,age,tall(m),weight,start_career,other club tournament,National_W,National_L,National_try,yellow,...,year,team,competition,pts,played,start,try,pen,red,min
0,Scrumhalf,27.0,1.74,86.0,2000.0,champions cup,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Backrow,30.0,1.90,103.0,2013.0,0,9.0,4.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Backrow,32.0,2.00,116.0,2013.0,0,10.0,2.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Backrow,26.0,193.00,106.0,2017.0,champions cup,12.0,2.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Secondrow,32.0,2.03,126.0,2013.0,Challenge Cup,10.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1612]:
final_rugby.columns

Index(['Position', 'age', 'tall(m)', 'weight', 'start_career',
       'other club tournament', 'National_W', 'National_L', 'National_try',
       'yellow', 'red ', 'year', 'team', 'competition', 'pts', 'played',
       'start', 'try', 'pen', 'red', 'min'],
      dtype='object')

In [1622]:
selected_cols = [
    'Position', 'age', 'tall(m)', 'weight', 'start_career',
       'other club tournament', 'National_W', 'National_L', 'National_try',
       'yellow', 'red ', 'year', 'team', 'competition', 'pts', 'played',
       'start', 'try', 'pen', 'red', 'min'
]

final_rugby = final_rugby[selected_cols]

In [1623]:
final_rugby = final_rugby.ffill()

In [1624]:
final_rugby.isna().sum()

Position                  0
age                       0
tall(m)                   0
weight                    0
start_career              0
other club tournament     0
National_W                0
National_L                0
National_try              0
yellow                    0
red                       0
year                     99
team                     99
competition              99
pts                      99
played                   99
start                    99
try                      99
pen                      99
red                      99
min                      99
dtype: int64

In [1625]:
# final_rugby.to_csv('cleaned_rugby.csv', index=False)

# Indoor Games

# Badminton Cleaning

In [1626]:
bad_df1 = pd.read_csv("Indoor/badminton/bwf_lky.csv")
bad_df1.head()

,Unnamed: 0,year,tournament,round,match_time,player1,player2,player1_set1,player2_set1,player1_set2,player2_set2,player1_set3,player2_set3
0,0,2021,TotalEnergies BWF World Championships 2021,R64,0:54,LOH Kean Yew,Viktor AXELSEN,14,21,21.0,9.0,21.0,6.0
1,1,2021,TotalEnergies BWF World Championships 2021,R32,0:25,Luka WRABER,LOH Kean Yew,4,21,8.0,21.0,NaN,NaN
2,2,2021,TotalEnergies BWF World Championships 2021,R16,0:30,Kantaphon WANGCHAROEN,LOH Kean Yew,4,21,7.0,21.0,NaN,NaN
3,3,2021,TotalEnergies BWF World Championships 2021,QF,0:43,PRANNOY H. S.,LOH Kean Yew,14,21,12.0,21.0,NaN,NaN
4,4,2021,TotalEnergies BWF World Championships 2021,SF,1:01,Anders ANTONSEN,LOH Kean Yew,21,23,14.0,21.0,NaN,NaN

In [1627]:
bad_df1.isnull().sum()

Unnamed: 0        0
year              0
tournament        0
round            11
match_time        0
player1           0
player2           0
player1_set1      5
player2_set1      6
player1_set2     11
player2_set2      9
player1_set3    144
player2_set3    144
dtype: int64

In [1628]:
columns_to_fill = [
    "year",
    "tournament",
    "round",
    "match_time",
    "player1",
    "player2",
    "player1_set1",
    "player2_set1",
    "player1_set2",
    "player2_set2",
    "player1_set3",
    "player2_set3"
]

for col in columns_to_fill:
    if col in bad_df1.columns:
        bad_df1[col] = bad_df1[col].fillna(0)

In [1629]:
bad_df1[columns_to_fill].isnull().sum()

year            0
tournament      0
round           0
match_time      0
player1         0
player2         0
player1_set1    0
player2_set1    0
player1_set2    0
player2_set2    0
player1_set3    0
player2_set3    0
dtype: int64

In [1630]:
# columns_to_drop = ["Unnamed: 0", "tournament", "match_time", "player1", "player2"
# ]

# bad_df1.drop(columns=columns_to_drop, inplace=True)

In [1631]:
bad_df1.head()

,Unnamed: 0,year,tournament,round,match_time,player1,player2,player1_set1,player2_set1,player1_set2,player2_set2,player1_set3,player2_set3
0,0,2021,TotalEnergies BWF World Championships 2021,R64,0:54,LOH Kean Yew,Viktor AXELSEN,14,21,21.0,9.0,21.0,6.0
1,1,2021,TotalEnergies BWF World Championships 2021,R32,0:25,Luka WRABER,LOH Kean Yew,4,21,8.0,21.0,0.0,0.0
2,2,2021,TotalEnergies BWF World Championships 2021,R16,0:30,Kantaphon WANGCHAROEN,LOH Kean Yew,4,21,7.0,21.0,0.0,0.0
3,3,2021,TotalEnergies BWF World Championships 2021,QF,0:43,PRANNOY H. S.,LOH Kean Yew,14,21,12.0,21.0,0.0,0.0
4,4,2021,TotalEnergies BWF World Championships 2021,SF,1:01,Anders ANTONSEN,LOH Kean Yew,21,23,14.0,21.0,0.0,0.0

In [1632]:
bad_df2 = pd.read_csv("Indoor/badminton/flashscore.csv")
bad_df2.head()

   Rank  Points  tournament                      Name Nationality
0     1   98715          14            Axelsen Viktor     Denmark
1     2   90984          19                 Shi Yu Qi       China
2     3   85101          20  Ginting Anthony Sinisuka   Indonesia
3     4   83594          19           Antonsen Anders     Denmark
4     5   81531          19          Christie Jonatan   Indonesia

In [1633]:
bad_df2.isnull().sum()

Rank           0
Points         0
tournament     0
Name           0
Nationality    0
dtype: int64

In [1634]:
bad_df2.head()

   Rank  Points  tournament                      Name Nationality
0     1   98715          14            Axelsen Viktor     Denmark
1     2   90984          19                 Shi Yu Qi       China
2     3   85101          20  Ginting Anthony Sinisuka   Indonesia
3     4   83594          19           Antonsen Anders     Denmark
4     5   81531          19          Christie Jonatan   Indonesia

In [1635]:
bad_df3 = pd.read_csv("Indoor/badminton/badminton.csv")
bad_df3.head()

,tournament,city,country,date,tournament_type,discipline,round,winner,nb_sets,retired,...,team_one_most_consecutive_points_game_2,team_two_most_consecutive_points_game_2,team_one_game_points_game_2,team_two_game_points_game_2,game_2_scores,team_one_most_consecutive_points_game_3,team_two_most_consecutive_points_game_3,team_one_game_points_game_3,team_two_game_points_game_3,game_3_scores
0,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MD,Qualification quarter final,1,3,False,...,2.0,3.0,0.0,1.0,"['0-0', '0-1', '0-2', '1-2', '1-3', '1-4', '2-...",7.0,3.0,1.0,0.0,"['0-0', '1-0', '2-0', '2-1', '2-2', '3-2', '3-..."
1,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MD,Qualification quarter final,1,2,False,...,7.0,3.0,4.0,0.0,"['0-0', '1-0', '1-1', '2-1', '2-2', '2-3', '3-...",NaN,NaN,NaN,NaN,[]
2,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MD,Qualification quarter final,2,3,False,...,3.0,3.0,2.0,3.0,"['0-0', '0-1', '0-2', '0-3', '1-3', '2-3', '2-...",3.0,6.0,0.0,1.0,"['0-0', '1-0', '1-1', '2-1', '2-2', '3-2', '4-..."
3,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,09-01-2018,HSBC BWF World Tour Super 300,MD,Qualification quarter final,2,2,False,...,3.0,5.0,0.0,3.0,"['0-0', '0-1', '1-1', '1-2', '2-2', '2-3', '2-...",NaN,NaN,NaN,NaN,[]
4,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Bangkok,Thailand,10-01-2018,HSBC BWF World Tour Super 300,MD,Round of 32,1,3,False,...,3.0,4.0,0.0,2.0,"['0-0', '0-1', '0-2', '1-2', '1-3', '1-4', '2-...",4.0,2.0,2.0,0.0,"['0-0', '0-1', '1-1', '1-2', '1-3', '2-3', '2-..."

In [1636]:
bad_df3.isnull().sum()

tournament                                    0
city                                          0
country                                       0
date                                          0
tournament_type                               0
discipline                                    0
round                                         0
winner                                        0
nb_sets                                       0
retired                                       0
game_1_score                                  0
game_2_score                                 15
game_3_score                               1859
team_one_player_one                           0
team_one_player_two                           0
team_two_player_one                           0
team_two_player_two                           0
team_one_player_one_nationality               0
team_one_player_two_nationality               0
team_two_player_one_nationality               0
team_two_player_two_nationality               0
team_one_total_points                         0
team_two_total_points                         0
team_one_most_consecutive_points              0
team_two_most_consecutive_points              0
team_one_game_points                          0
team_two_game_points                          0
team_one_most_consecutive_points_game_1       0
team_two_most_consecutive_points_game_1       0
team_one_game_points_game_1                   0
team_two_game_points_game_1                   0
game_1_scores                                 0
team_one_most_consecutive_points_game_2      15
team_two_most_consecutive_points_game_2      15
team_one_game_points_game_2                  15
team_two_game_points_game_2                  15
game_2_scores                                11
team_one_most_consecutive_points_game_3    1861
team_two_most_consecutive_points_game_3    1861
team_one_game_points_game_3                1861
team_two_game_points_game_3                1861
game_3_scores                                15
dtype: int64

In [1637]:
columns_to_drop = ["city", "country", "date", "tournament_type", "discipline", "winner", "game_1_score", "game_2_score", "game_3_score", 
                   "team_one_player_one", "team_one_player_two", "team_two_player_one", "team_two_player_two", "team_one_player_one_nationality", 
                   "team_one_player_two_nationality" ,"team_two_player_one_nationality","team_two_player_two_nationality", "team_one_total_points", 
                   "team_two_total_points", "team_one_most_consecutive_points", "team_two_most_consecutive_points", "team_one_game_points", 
                   "team_two_game_points", "team_one_most_consecutive_points_game_1", "team_two_most_consecutive_points_game_1", 
                   "team_one_game_points_game_1", "team_two_game_points_game_1", "game_1_scores", "game_2_scores", "team_one_most_consecutive_points_game_3", "team_two_most_consecutive_points_game_3", "team_one_game_points_game_3", "team_two_game_points_game_3", "game_3_scores"
]

bad_df3.drop(columns=columns_to_drop, inplace=True)

In [1638]:
bad_df3.isnull().sum()

tournament                                  0
round                                       0
nb_sets                                     0
retired                                     0
team_one_most_consecutive_points_game_2    15
team_two_most_consecutive_points_game_2    15
team_one_game_points_game_2                15
team_two_game_points_game_2                15
dtype: int64

In [1639]:
bad_df3.head()

,tournament,round,nb_sets,retired,team_one_most_consecutive_points_game_2,team_two_most_consecutive_points_game_2,team_one_game_points_game_2,team_two_game_points_game_2
0,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Qualification quarter final,3,False,2.0,3.0,0.0,1.0
1,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Qualification quarter final,2,False,7.0,3.0,4.0,0.0
2,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Qualification quarter final,3,False,3.0,3.0,2.0,3.0
3,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Qualification quarter final,2,False,3.0,5.0,0.0,3.0
4,PRINCESS SIRIVANNAVARI Thailand Masters 2018,Round of 32,3,False,3.0,4.0,0.0,2.0

In [1640]:
# Step 1: Standardize player names in both datasets
bad_df1['player1'] = bad_df1['player1'].str.strip().str.lower()
bad_df1['player2'] = bad_df1['player2'].str.strip().str.lower()
bad_df2['Name'] = bad_df2['Name'].str.strip().str.lower()

# Step 2: Merge the datasets using standardized player names
final_bad = pd.merge(bad_df1, bad_df2, left_on="player1", right_on="Name", how="inner")
final_bad = pd.merge(final_bad, bad_df2, left_on="player2", right_on="Name", how="inner", suffixes=('_player1', '_player2'))

# Step 3: Select relevant columns after merge
selected_columns= [
    'year', 'tournament', 'player1', 'player2', 'player1_set1', 'player2_set1', 
    'player1_set2', 'player2_set2', 'player1_set3', 'player2_set3', 'Points_player1', 
    'Points_player2', 'Rank_player1', 'Rank_player2', 'Nationality_player1', 'Nationality_player2'
]

# Clean and select relevant columns
final_bad = final_bad[selected_columns]

# Display the cleaned merged dataset
final_bad.head()

,year,tournament,player1,player2,player1_set1,player2_set1,player1_set2,player2_set2,player1_set3,player2_set3,Points_player1,Points_player2,Rank_player1,Rank_player2,Nationality_player1,Nationality_player2
0,2021,24,prannoy h. s.,loh kean yew,14,21,12.0,21.0,0.0,0.0,77647,69912,9,10,India,Singapore
1,2021,29,loh kean yew,wang tzu wei,17,21,21.0,14.0,21.0,15.0,69912,52710,10,24,Singapore,Taiwan
2,2021,24,chou tien chen,loh kean yew,21,10,21.0,12.0,0.0,0.0,62498,69912,15,10,Taiwan,Singapore
3,2021,24,chou tien chen,loh kean yew,18,21,13.0,21.0,0.0,0.0,62498,69912,15,10,Taiwan,Singapore
4,2021,24,loh kean yew,lee zii jia,19,21,21.0,13.0,17.0,12.0,69912,68296,10,11,Singapore,Malaysia

In [1641]:
# final_bad.to_csv('cleaned_badminton.csv', index=False)

# Baseball Data

In [1642]:
base_df1 = pd.read_csv("Indoor/baseball/mlb_player_stats_hitter_2024.csv")
base_df1.head()

,playerID,TEAM,G,AtBat,Runs,Hits,2B,3B,HR,RBI,BB,SO,SB,CS,AVG,OBP,SLG,OPS
0,1\nAaronJudge\nCF,NYY,158,559,122,180,36,1,58,144,133,171,10,0,0.322,0.458,0.701,1.159
1,2\nShoheiOhtani\nDH,LAD,159,636,134,197,38,7,54,130,81,162,59,4,0.31,0.39,0.646,1.036
2,3\nJuanSoto\nRF,NYY,157,576,128,166,31,4,41,109,129,119,7,4,0.288,0.419,0.569,0.988
3,4\nBobbyWitt\nSS,KC,161,636,125,211,45,11,32,109,57,106,31,12,0.332,0.389,0.588,0.977
4,5\nYordanAlvarez\nDH,HOU,147,552,88,170,34,2,35,86,69,95,6,0,0.308,0.392,0.567,0.959

In [1643]:
columns_to_drop = ["G", "2B", "3B", "SB", "CS", "OPS"]

base_df1.drop(columns=columns_to_drop, inplace=True)

In [1644]:
base_df1.head()

,playerID,TEAM,AtBat,Runs,Hits,HR,RBI,BB,SO,AVG,OBP,SLG
0,1\nAaronJudge\nCF,NYY,559,122,180,58,144,133,171,0.322,0.458,0.701
1,2\nShoheiOhtani\nDH,LAD,636,134,197,54,130,81,162,0.31,0.39,0.646
2,3\nJuanSoto\nRF,NYY,576,128,166,41,109,129,119,0.288,0.419,0.569
3,4\nBobbyWitt\nSS,KC,636,125,211,32,109,57,106,0.332,0.389,0.588
4,5\nYordanAlvarez\nDH,HOU,552,88,170,35,86,69,95,0.308,0.392,0.567

In [1645]:
base_df2 = pd.read_csv("Indoor/baseball/Hitters - Hitters.csv.csv")
base_df2

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,TEAM,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,293,66,1,30,29,14,1,293,66,1,30,29,14,A,E,446,33,20,NaN,A
1,315,81,7,24,38,39,14,3449,835,69,321,414,375,N,W,632,43,10,475.0,N
2,479,130,18,66,72,76,3,1624,457,63,224,266,263,A,W,880,82,14,480.0,A
3,496,141,20,65,78,37,11,5628,1575,225,828,838,354,N,E,200,11,3,500.0,N
4,321,87,10,39,42,30,2,396,101,12,48,46,33,N,E,805,40,4,91.5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,497,127,7,65,48,37,5,2703,806,32,379,311,138,N,E,325,9,3,700.0,N
318,492,136,5,76,50,94,12,5511,1511,39,897,451,875,A,E,313,381,20,875.0,A
319,475,126,3,61,43,52,6,1700,433,7,217,93,146,A,W,37,113,7,385.0,A
320,573,144,9,85,60,78,8,3198,857,97,470,420,332,A,E,1314,131,12,960.0,A
321,631,170,9,77,44,31,11,4908,1457,30,775,357,249,A,W,408,4,3,1000.0,A

In [1646]:
base_df2.isnull().sum()

AtBat         0
Hits          0
HmRun         0
Runs          0
RBI           0
Walks         0
Years         0
CAtBat        0
CHits         0
CHmRun        0
CRuns         0
CRBI          0
CWalks        0
TEAM          0
Division      0
PutOuts       0
Assists       0
Errors        0
Salary       59
NewLeague     0
dtype: int64

In [1647]:
columns_to_drop = ["Runs", "Years", "CAtBat", "CHits", "CHmRun", "CRuns", "CRBI", "CWalks", "Division", "Errors", "Salary", "NewLeague"]

base_df2.drop(columns=columns_to_drop, inplace=True)
base_df2

     AtBat  Hits  HmRun  RBI  Walks TEAM  PutOuts  Assists
0      293    66      1   29     14    A      446       33
1      315    81      7   38     39    N      632       43
2      479   130     18   72     76    A      880       82
3      496   141     20   78     37    N      200       11
4      321    87     10   42     30    N      805       40
..     ...   ...    ...  ...    ...  ...      ...      ...
317    497   127      7   48     37    N      325        9
318    492   136      5   50     94    A      313      381
319    475   126      3   43     52    A       37      113
320    573   144      9   60     78    A     1314      131
321    631   170      9   44     31    A      408        4

[322 rows x 8 columns]

In [1648]:
columns_to_fill = [
    "AtBat",
    "Hits",	
    "HmRun",
    "RBI",
    "Walks",
    "PutOuts",
    "Assists"
]

for col in columns_to_fill:
    if col in base_df2.columns:
        base_df2[col] = base_df2[col].fillna(0)

base_df2[columns_to_fill].isnull().sum()

AtBat      0
Hits       0
HmRun      0
RBI        0
Walks      0
PutOuts    0
Assists    0
dtype: int64

In [1649]:
base_df2.head()

   AtBat  Hits  HmRun  RBI  Walks TEAM  PutOuts  Assists
0    293    66      1   29     14    A      446       33
1    315    81      7   38     39    N      632       43
2    479   130     18   72     76    A      880       82
3    496   141     20   78     37    N      200       11
4    321    87     10   42     30    N      805       40

In [1650]:
base_df3 = pd.read_csv("Indoor/baseball/Baseball.csv")
base_df3.head()

    playerID  yearID  gameNum        gameID teamID lgID   GP  startingPos
0  gomezle01    1933        0  ALS193307060    NYA   AL  1.0          1.0
1  ferreri01    1933        0  ALS193307060    BOS   AL  1.0          2.0
2  gehrilo01    1933        0  ALS193307060    NYA   AL  1.0          3.0
3  gehrich01    1933        0  ALS193307060    DET   AL  1.0          4.0
4  dykesji01    1933        0  ALS193307060    CHA   AL  1.0          5.0

In [1651]:
base_df3.isnull().sum()

playerID          0
yearID            0
gameNum           0
gameID           49
teamID            0
lgID              0
GP               19
startingPos    3489
dtype: int64

In [1652]:
columns_to_drop = ['startingPos', 'gameID']

base_df3.drop(columns=columns_to_drop, inplace=True)

In [1653]:
base_df3.isnull().sum()

playerID     0
yearID       0
gameNum      0
teamID       0
lgID         0
GP          19
dtype: int64

In [1654]:
columns_to_fill = [
    "playerID",
    "yearID",
    "gameNum",
    "teamID",
    "lgID",
    "GP"
]

for col in columns_to_fill:
    if col in base_df3.columns:
        base_df3[col] = base_df3[col].fillna(0)

In [1655]:
base_df3.isnull().sum()

playerID    0
yearID      0
gameNum     0
teamID      0
lgID        0
GP          0
dtype: int64

In [1656]:
base_df3.head()

    playerID  yearID  gameNum teamID lgID   GP
0  gomezle01    1933        0    NYA   AL  1.0
1  ferreri01    1933        0    BOS   AL  1.0
2  gehrilo01    1933        0    NYA   AL  1.0
3  gehrich01    1933        0    DET   AL  1.0
4  dykesji01    1933        0    CHA   AL  1.0

In [1657]:
final_base = pd.concat([base_df1, base_df2], axis=0)
# final_base.dtypes
final_base.isna().sum()

playerID    322
TEAM          0
AtBat         0
Runs        322
Hits          0
HR          322
RBI           0
BB          322
SO          322
AVG         322
OBP         322
SLG         322
HmRun       134
Walks       134
PutOuts     134
Assists     134
dtype: int64

In [1658]:
# final_base.fillna()
final_base = final_base.ffill()
# df['BB'].fillna(df['BB'].mean())

In [1659]:
final_base.isna().sum()

playerID      0
TEAM          0
AtBat         0
Runs          0
Hits          0
HR            0
RBI           0
BB            0
SO            0
AVG           0
OBP           0
SLG           0
HmRun       134
Walks       134
PutOuts     134
Assists     134
dtype: int64

In [1660]:
# final_base.to_csv('cleaned_baseball.csv', index=False)

# Table tennis Data

In [1661]:
table_df1 = pd.read_csv("Indoor/tabletennis/table_tennis.csv")
table_df1.head()

,X,Date,Time,Player1,Player2,Sets_P1,Sets_P2,P1_G1,P2_G1,P1_G2,P2_G2,P1_G3,P2_G3,P1_G4,P2_G4,P1_G5,P2_G5,HomeWinner
0,1,6/10/2022,1:05:00,Marchuk M.,Polysynskyi M.,3,1,11,8,11,6,6,11,11.0,8.0,NaN,NaN,1
1,2,6/10/2022,1:25:00,Sokolov S.,Sachuk S.,0,3,12,14,8,11,5,11,NaN,NaN,NaN,NaN,0
2,3,6/10/2022,1:35:00,Samofal Y.,Bambutsa R.,3,1,4,11,11,5,11,6,11.0,9.0,NaN,NaN,1
3,4,6/10/2022,1:55:00,Kyilo V.,Chernyshov D.,3,1,6,11,11,1,15,13,11.0,7.0,NaN,NaN,1
4,5,6/10/2022,2:05:00,Polysynskyi M.,Kostiuk B.,3,0,12,10,11,9,11,6,NaN,NaN,NaN,NaN,1

In [1662]:
table_df1.isnull().sum()

X                0
Date             0
Time             0
Player1          0
Player2          0
Sets_P1          0
Sets_P2          0
P1_G1            0
P2_G1            0
P1_G2            0
P2_G2            0
P1_G3            0
P2_G3            0
P1_G4         2403
P2_G4         2403
P1_G5         5333
P2_G5         5333
HomeWinner       0
dtype: int64

In [1663]:
columns_to_drop = ["P1_G3", "P2_G3", "P1_G4", "P2_G4", "P1_G5", "P2_G5"]

table_df1.drop(columns=columns_to_drop, inplace=True)
table_df1.head()

,X,Date,Time,Player1,Player2,Sets_P1,Sets_P2,P1_G1,P2_G1,P1_G2,P2_G2,HomeWinner
0,1,6/10/2022,1:05:00,Marchuk M.,Polysynskyi M.,3,1,11,8,11,6,1
1,2,6/10/2022,1:25:00,Sokolov S.,Sachuk S.,0,3,12,14,8,11,0
2,3,6/10/2022,1:35:00,Samofal Y.,Bambutsa R.,3,1,4,11,11,5,1
3,4,6/10/2022,1:55:00,Kyilo V.,Chernyshov D.,3,1,6,11,11,1,1
4,5,6/10/2022,2:05:00,Polysynskyi M.,Kostiuk B.,3,0,12,10,11,9,1

In [1664]:
table_df1.isnull().sum()

X             0
Date          0
Time          0
Player1       0
Player2       0
Sets_P1       0
Sets_P2       0
P1_G1         0
P2_G1         0
P1_G2         0
P2_G2         0
HomeWinner    0
dtype: int64

In [1665]:
table_df1.head()

,X,Date,Time,Player1,Player2,Sets_P1,Sets_P2,P1_G1,P2_G1,P1_G2,P2_G2,HomeWinner
0,1,6/10/2022,1:05:00,Marchuk M.,Polysynskyi M.,3,1,11,8,11,6,1
1,2,6/10/2022,1:25:00,Sokolov S.,Sachuk S.,0,3,12,14,8,11,0
2,3,6/10/2022,1:35:00,Samofal Y.,Bambutsa R.,3,1,4,11,11,5,1
3,4,6/10/2022,1:55:00,Kyilo V.,Chernyshov D.,3,1,6,11,11,1,1
4,5,6/10/2022,2:05:00,Polysynskyi M.,Kostiuk B.,3,0,12,10,11,9,1

In [1666]:
table_df2 = pd.read_csv("Indoor/tabletennis/tabletennis2.csv")
table_df2.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.co...",False,1,Italy,IT,ITA,NaN,NaN,NaN,NaN
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en...",False,2,Norway,NO,NOR,NaN,NaN,NaN,NaN
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/at...",False,3,Sweden,SE,SWE,NaN,NaN,NaN,NaN
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/a...",False,4,Great Britain,GB,GBR,NaN,NaN,NaN,NaN
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/ath...",False,5,Canada,CA,CAN,NaN,NaN,NaN,NaN

In [1667]:
table_df2.isnull().sum()

discipline_title              0
event_title                   0
slug_game                     0
participant_type              0
medal_type               142598
athletes                 154828
rank_equal               130278
rank_position              3878
country_name                  0
country_code               5036
country_3_letter_code         0
athlete_url               32813
athlete_full_name         21158
value_unit                84158
value_type                72755
dtype: int64

In [1668]:
columns_to_drop = ["medal_type", "rank_equal", "rank_position", "country_name", "country_code", "country_3_letter_code", "athlete_url", 
                   "athlete_full_name", "value_unit", "value_type"]

table_df2.drop(columns=columns_to_drop, inplace=True)

In [1669]:
table_df2.isnull().sum()

discipline_title         0
event_title              0
slug_game                0
participant_type         0
athletes            154828
dtype: int64

# Volleyball

In [1692]:
volley_df1 = pd.read_csv("Indoor/volleyball/VNL2023 - VNL2023.csv.csv")
volley_df1.head()

,player,country,age,attack,block,serve,set,dig,receive,position
0,Ichikawa Yuki,Japan,28,15.80,1.13,1.40,0.07,4.80,5.60,OH
1,Romano Yuri,Italy,26,12.33,1.07,1.47,0.00,3.87,0.00,OP
2,Abdel-Aziz Nimir,Nederland,31,15.33,0.67,2.08,0.00,3.17,0.25,OP
3,Herrera Jaime Jesus,Cuba,28,15.00,0.92,1.75,0.00,3.33,0.17,OP
4,Takahashi Ran,Japan,22,11.53,0.67,1.00,0.07,6.40,5.07,OH

In [1693]:
volley_df1.isnull().sum()

player      0
country     0
age         0
attack      0
block       0
serve       0
set         0
dig         0
receive     0
position    0
dtype: int64

In [1694]:
columns_to_drop = ["country", "position"]

volley_df1.drop(columns=columns_to_drop, inplace=True)

In [1695]:
volley_df1.head()

                player  age  attack  block  serve   set   dig  receive
0        Ichikawa Yuki   28   15.80   1.13   1.40  0.07  4.80     5.60
1          Romano Yuri   26   12.33   1.07   1.47  0.00  3.87     0.00
2     Abdel-Aziz Nimir   31   15.33   0.67   2.08  0.00  3.17     0.25
3  Herrera Jaime Jesus   28   15.00   0.92   1.75  0.00  3.33     0.17
4        Takahashi Ran   22   11.53   0.67   1.00  0.07  6.40     5.07

In [1696]:
volley_df2 = pd.read_csv("Indoor/volleyball/vnl2024.csv")
volley_df2.head()

    player country  age  attack  block  serve  set    dig  receive position
0   Vargas     TUR   24   20.25   1.62   1.50  0.0   7.75     0.00       OP
1     Koga     JPN   28   17.67   0.78   1.11  0.0  11.22     1.11       OH
2  Van Ryk     CAN   25   16.44   0.89   1.11  0.0  12.56     0.11       OH
3  Li Y.Y.     CHN   24   16.33   0.56   1.00  0.0   8.22     3.56       OH
4     Gray     CAN   30   15.22   0.44   1.00  0.0   9.44     5.56       OH

In [1697]:
volley_df2.isnull().sum()

player      0
country     0
age         0
attack      0
block       0
serve       0
set         0
dig         0
receive     0
position    0
dtype: int64

In [1698]:
volley_df2.head()

    player country  age  attack  block  serve  set    dig  receive position
0   Vargas     TUR   24   20.25   1.62   1.50  0.0   7.75     0.00       OP
1     Koga     JPN   28   17.67   0.78   1.11  0.0  11.22     1.11       OH
2  Van Ryk     CAN   25   16.44   0.89   1.11  0.0  12.56     0.11       OH
3  Li Y.Y.     CHN   24   16.33   0.56   1.00  0.0   8.22     3.56       OH
4     Gray     CAN   30   15.22   0.44   1.00  0.0   9.44     5.56       OH

In [1699]:
columns_to_drop = ["country", "position"]

volley_df2.drop(columns=columns_to_drop, inplace=True)

In [1700]:
volley_df3 = pd.read_csv("Indoor/volleyball/volleyball21_23.csv")
volley_df3.head()

,Player_ID,Year,TeamA,TeamB,Serve_Points,Serve_Errors,Serve_Attempts,Total_Serves,Match_Date,Set_Successes,...,Block_Rebounds,Total_Blocks,Reception_Successful,Reception_Errors,Reception_Attemps,Total_Receptions,Dig_Success,Dig_Errors,Dig_Attempts,Total_Digs
0,142412,2021,Iran,Argentina,0,0,0,0,23/06/2021,2,...,0,0,0,0,0,0,1,0,0,1
1,142412,2021,France,Argentina,0,0,1,1,22/06/2021,2,...,0,0,0,0,0,0,0,0,0,0
2,142412,2021,Argentina,Serbia,1,1,11,13,17/06/2021,25,...,0,0,0,0,0,0,5,0,1,6
3,142412,2021,Argentina,Bulgaria,0,0,0,0,15/06/2021,2,...,0,0,0,0,0,0,1,0,0,1
4,142412,2021,Japan,Argentina,0,0,1,1,11/06/2021,7,...,0,0,0,0,0,0,0,0,0,0

In [1701]:
volley_df3.isnull().sum()

Player_ID                 0
Year                      0
TeamA                   108
TeamB                   108
Serve_Points              0
Serve_Errors              0
Serve_Attempts            0
Total_Serves              0
Match_Date                0
Set_Successes             4
Set_Errors                4
Set_Attempts              4
Total_Sets                4
Attack_Success            0
Attack Errors             0
Attack_Attempts           0
Total_Attacks             0
Block_Successful          0
Block_Errors              0
Block_Rebounds            0
Total_Blocks              0
Reception_Successful     15
Reception_Errors         15
Reception_Attemps        15
Total_Receptions         15
Dig_Success               0
Dig_Errors                0
Dig_Attempts              0
Total_Digs                0
dtype: int64

In [1702]:
columns_to_fill = [
    "Year", "Serve_Points", "Serve_Errors", "Serve_Attempts", "Total_Serves", "Set_Successes", "Set_Errors", "Set_Attempts", "Total_Sets",
    "Attack_Success", "Attack Errors", "Attack_Attempts", "Total_Attacks", "Block_Successful", "Block_Errors", "Block_Rebounds", "Total_Blocks",
    "Reception_Successful", "Reception_Errors", "Reception_Attempts", "Total_Receptions", "Dig_Success", "Dig_Errors", "Dig_Attempts", "Total_Digs"
]

for col in columns_to_fill:
    if col in volley_df3.columns:
        cric_df1[col] = volley_df3[col].fillna(1)

columns_to_drop = ["Year", "TeamA", "TeamB", "Serve_Points", "Serve_Errors", "Match_Date", "Set_Successes", "Set_Errors", "Set_Attempts", 
                   "Total_Sets", "Attack_Success", "Attack Errors", "Attack_Attempts", "Total_Attacks", "Block_Successful", "Block_Errors", 
                   "Block_Rebounds", "Reception_Successful", "Reception_Errors", "Reception_Attemps", "Total_Receptions", "Dig_Success", "Dig_Errors"
]

In [1703]:
volley_df3.drop(columns=columns_to_drop, inplace=True)
volley_df3.head()

   Player_ID Serve_Attempts Total_Serves Total_Blocks Dig_Attempts Total_Digs
0     142412              0            0            0            0          1
1     142412              1            1            0            0          0
2     142412             11           13            0            1          6
3     142412              0            0            0            0          1
4     142412              1            1            0            0          0

In [1704]:
con = pd.concat([volley_df1, volley_df2], axis=0)

In [1705]:
con

                  player  age  attack  block  serve   set   dig  receive
0          Ichikawa Yuki   28   15.80   1.13   1.40  0.07  4.80     5.60
1            Romano Yuri   26   12.33   1.07   1.47  0.00  3.87     0.00
2       Abdel-Aziz Nimir   31   15.33   0.67   2.08  0.00  3.17     0.25
3    Herrera Jaime Jesus   28   15.00   0.92   1.75  0.00  3.33     0.17
4          Takahashi Ran   22   11.53   0.67   1.00  0.07  6.40     5.07
..                   ...  ...     ...    ...    ...   ...   ...      ...
262            Rodriguez   24    0.00   0.00   0.00  0.11  5.22     1.67
263              Reesink   26    0.00   0.00   0.00  0.00  9.33     3.33
264                Pušić   31    0.00   0.00   0.00  0.00  5.75     2.12
265                 Jost   24    0.00   0.00   0.00  0.00  5.33     1.11
266           Kowalewska   32    0.00   0.00   0.00  5.50  1.25     0.00

[398 rows x 8 columns]

In [1706]:
con.isna().sum()

player     0
age        0
attack     0
block      0
serve      0
set        0
dig        0
receive    0
dtype: int64

In [1707]:
# con.to_csv('cleaned_volley.csv', index=False)